function [pop] = makeFakePop(numCells, varargin)
% Function to make a population of fake cells of classdef 'fakeCell'
% Usage: [pop] = makeFakePop(numCells)
% Optional arguments: that specify the type of population and dependence
%     'type' 'dimensions' 'bins' ...
%     'Pcen' 'Pspread' 'Palpha'...
%     'Vcen' 'Vspread' ...
%     'Rcen' 'Rspread' ...
%     'Mcen' 'Mspread' 'Mangle' ...
%  
% Aman Saleem
% July 2013

if nargin<1 || isempty(numCells)
    error(message('Need to enter at least number of cells'));
end

pnames = {'type' 'dimensions' 'bins' ...
    'Pcen' 'Pspread' 'Palpha'...
    'Vcen' 'Vspread' ...
    'Rcen' 'Rspread' ...
    'Mcen' 'Mspread' 'Mangle' ...
    };
dflts = {'P' 1 [50 30 30] ...
    0 0 1 ...
    30 15 ...
    30 15 ...
    30 15 45 ...
    };

[type, dimensions, bins, ...
    Pcen, Pspread, Palpha, Vcen, Vspread, ...
    Rcen, Rspread, Mcen, Mspread, Mangle] = ...
    internal.stats.parseArgs(pnames,dflts,varargin{:});

if Pcen==0
    Pbins = bins(1);
    Pcen = 0.01 + Pbins*rand(numCells,1);%(0.01:(Pbins/numCells):Pbins)';
end

if Pspread==0
    Pspread = 30 + 25*(rand(numCells,1)-0.5);
end

if size(Pcen,1)==1; Pcen(2:numCells,:) = Pcen(1,:); end
if length(Vcen)==1; Vcen(2:numCells) = Vcen(1); end
if length(Rcen)==1; Rcen(2:numCells) = Rcen(1); end
if length(Mcen)==1; Mcen(2:numCells) = Mcen(1); end

if size(Pspread,1)==1; Pspread(2:numCells,:) = Pspread(1,:); end
if length(Vspread)==1; Vspread(2:numCells) = Vspread(1); end
if length(Rspread)==1; Rspread(2:numCells) = Rspread(1); end
if length(Mspread)==1; Mspread(2:numCells) = Mspread(1); end

if size(Palpha,2)==1; Palpha(2:numCells,:) = Palpha(1,:); end
if length(Mangle)==1; Mangle(2:numCells) = Mangle(1); end

for icell = 1:numCells
    pop(icell) = fakeCell(...
        'type', type, 'dimensions', dimensions, 'bins', bins, ...
        'Pcen', Pcen(icell,:), 'Pspread', Pspread(icell,:), 'Palpha', Palpha(icell,:), ...
        'Vcen', Vcen(icell), 'Vspread', Vspread(icell), ...
        'Rcen', Rcen(icell), 'Rspread', Rspread(icell), ...
        'Mcen', Mcen(icell), 'Mspread', Mspread(icell), 'Mangle', Mangle);
    pop(icell) = makeFakeCell(pop(icell));
end